name: E2E Tests

on:
    workflow_dispatch:
    workflow_call:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    checks: write
    pull-requests: write

jobs:
    e2e_tests:
        name: Run E2E Tests
        runs-on: codebuild-ThorGHA-${{ github.run_id }}-${{ github.run_attempt }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install Node Modules
              run: yarn install

            - name: Start Private Network
              working-directory: ./network
              run: docker compose up -d --wait

            - name: Run Tests
              run: yarn test:fast

            - name: Publish Results
              uses: dorny/test-reporter@v1
              id: test-reporter
              if: success() || failure() # run this step even if previous step failed
              with:
                  name: E2E Test Report
                  only-summary: 'false'
                  list-suites: 'all'
                  list-tests: 'all'
                  fail-on-error: 'true'
                  reporter: 'jest-junit'
                  path: |
                      junit.xml
